# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: boss_mqtt.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'boss_mqtt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62oss_mqtt.proto\x12\x04\x62oss\"9\n\x0cTechwolfUser\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x07 \x01(\x05\"E\n\x13TechwolfMessageBody\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x12\n\ntemplateId\x18\x02 \x01(\x05\x12\x0c\n\x04text\x18\x03 \x01(\t\"\xa5\x01\n\x0fTechwolfMessage\x12 \n\x04\x66rom\x18\x01 \x01(\x0b\x32\x12.boss.TechwolfUser\x12\x1e\n\x02to\x18\x02 \x01(\x0b\x32\x12.boss.TechwolfUser\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12\x0b\n\x03mid\x18\x04 \x01(\x03\x12\'\n\x04\x62ody\x18\x06 \x01(\x0b\x32\x19.boss.TechwolfMessageBody\x12\x0c\n\x04\x63mid\x18\x0b \x01(\x03\"M\n\x14TechwolfChatProtocol\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\'\n\x08messages\x18\x03 \x03(\x0b\x32\x15.boss.TechwolfMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'boss_mqtt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TECHWOLFUSER']._serialized_start=25
  _globals['_TECHWOLFUSER']._serialized_end=82
  _globals['_TECHWOLFMESSAGEBODY']._serialized_start=84
  _globals['_TECHWOLFMESSAGEBODY']._serialized_end=153
  _globals['_TECHWOLFMESSAGE']._serialized_start=156
  _globals['_TECHWOLFMESSAGE']._serialized_end=321
  _globals['_TECHWOLFCHATPROTOCOL']._serialized_start=323
  _globals['_TECHWOLFCHATPROTOCOL']._serialized_end=400
# @@protoc_insertion_point(module_scope)
